// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/details/:type/:id": {
    params: {
      "type": string;
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/details/:type/:id";
  };
  "./pages/layout/PageLayout.tsx": {
    id: "pages/layout/PageLayout";
    page: "/" | "/details/:type/:id";
  };
  "pages/SearchPage.tsx": {
    id: "pages/SearchPage";
    page: "/";
  };
  "pages/details/DetailsPage.tsx": {
    id: "pages/details/DetailsPage";
    page: "/details/:type/:id";
  };
};